#!/bin/bash

# Display name migration script
echo "=========================================="
echo "🔧 Display Name Migration Instructions"
echo "=========================================="
echo ""
echo "Since you're using a hosted Supabase instance, you need to apply"
echo "the migration using the Supabase SQL Editor."
echo ""
echo "📋 Instructions:"
echo ""
echo "1. Open your Supabase dashboard:"
echo "   https://ubevbnynycrzjebxctme.supabase.co"
echo ""
echo "2. Navigate to: SQL Editor (in left sidebar)"
echo ""
echo "3. Create a new query and paste the migration SQL below"
echo ""
echo "4. Click 'Run' to execute the migration"
echo ""
echo "=========================================="
echo "📄 Migration SQL:"
echo "=========================================="
echo ""
cat supabase/migrations/001_add_display_name.sql
echo ""
echo ""
echo "=========================================="
echo "✅ After running the migration, test:"
echo "=========================================="
echo "1. Try signing up with a new account"
echo "2. Go to Settings and edit your display name"
echo "3. Verify display names show correctly in chat"
echo ""
